"""Create table KORISNIK.

Revision ID: 5cf708da243f
Revises: 
Create Date: 2023-11-08 00:42:07.560643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf708da243f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('korisnik',
    sa.Column('korisnikid', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=128), nullable=False),
    sa.Column('prezime', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('lozinka', sa.String(length=64), nullable=False),
    sa.Column('korisnikstvorenna', sa.TIMESTAMP(), nullable=False),
    sa.Column('uloga', sa.String(length=64), nullable=False),
    sa.Column('promijeniolozinku', sa.Boolean(), nullable=False),
    sa.CheckConstraint("uloga = ANY(ARRAY['admin','ucenik'])", name='chk_uloga'),
    sa.PrimaryKeyConstraint('korisnikid'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('korisnik')
    # ### end Alembic commands ###
