"""Add ON DELETE CASCADE to all foreign keys.

Revision ID: 59371dd7aa68
Revises: 32411e67745b
Create Date: 2024-01-08 13:50:37.392189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59371dd7aa68'
down_revision = '32411e67745b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.drop_constraint('dictionary_languageid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'language', ['languageid'], ['languageid'], ondelete='CASCADE')

    with op.batch_alter_table('phrase', schema=None) as batch_op:
        batch_op.drop_constraint('phrase_wordid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'word', ['wordid'], ['wordid'], ondelete='CASCADE')

    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_constraint('word_languageid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'language', ['languageid'], ['languageid'], ondelete='CASCADE')

    with op.batch_alter_table('word_dictionary', schema=None) as batch_op:
        batch_op.drop_constraint('word_dictionary_wordid_fkey', type_='foreignkey')
        batch_op.drop_constraint('word_dictionary_dictionaryid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'dictionary', ['dictionaryid'], ['dictionaryid'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'word', ['wordid'], ['wordid'], ondelete='CASCADE')

    with op.batch_alter_table('word_state', schema=None) as batch_op:
        batch_op.drop_constraint('word_state_bowlid_fkey', type_='foreignkey')
        batch_op.drop_constraint('word_state_wordid_fkey', type_='foreignkey')
        batch_op.drop_constraint('word_state_userid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['userid'], ['userid'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'bowl', ['bowlid'], ['bowlid'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'word', ['wordid'], ['wordid'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('word_state_userid_fkey', 'user', ['userid'], ['userid'])
        batch_op.create_foreign_key('word_state_wordid_fkey', 'word', ['wordid'], ['wordid'])
        batch_op.create_foreign_key('word_state_bowlid_fkey', 'bowl', ['bowlid'], ['bowlid'])

    with op.batch_alter_table('word_dictionary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('word_dictionary_dictionaryid_fkey', 'dictionary', ['dictionaryid'], ['dictionaryid'])
        batch_op.create_foreign_key('word_dictionary_wordid_fkey', 'word', ['wordid'], ['wordid'])

    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('word_languageid_fkey', 'language', ['languageid'], ['languageid'])

    with op.batch_alter_table('phrase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('phrase_wordid_fkey', 'word', ['wordid'], ['wordid'])

    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('dictionary_languageid_fkey', 'language', ['languageid'], ['languageid'])

    # ### end Alembic commands ###
