"""Add LANGUAGE and DICTIONARY tables.

Revision ID: 8053ef890252
Revises: f2c79148c4bf
Create Date: 2023-12-20 19:19:10.950962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8053ef890252'
down_revision = 'f2c79148c4bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('languageid', sa.Integer(), nullable=False),
    sa.Column('languagename', sa.String(length=128), nullable=False),
    sa.Column('isocode', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('languageid')
    )
    op.create_table('dictionary',
    sa.Column('dictionaryid', sa.Integer(), nullable=False),
    sa.Column('dictionaryname', sa.String(length=128), nullable=False),
    sa.Column('dictionarycreatedat', sa.TIMESTAMP(), nullable=False),
    sa.Column('languageid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['languageid'], ['language.languageid'], ),
    sa.PrimaryKeyConstraint('dictionaryid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dictionary')
    op.drop_table('language')
    # ### end Alembic commands ###
