"""Add UNIQUE constraint to LAANGUAGE.isocode.

Revision ID: 80bff2111857
Revises: 8053ef890252
Create Date: 2023-12-20 19:24:27.494967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80bff2111857'
down_revision = '8053ef890252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['isocode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
