"""Create table WORD.

Revision ID: f213c8eb2e84
Revises: 80bff2111857
Create Date: 2023-12-27 02:10:53.047971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f213c8eb2e84'
down_revision = '80bff2111857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('wordid', sa.Integer(), nullable=False),
    sa.Column('croatianname', sa.String(length=128), nullable=False),
    sa.Column('foreignname', sa.String(length=128), nullable=False),
    sa.Column('audiopath', sa.String(length=128), nullable=False),
    sa.Column('languageid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['languageid'], ['language.languageid'], ),
    sa.PrimaryKeyConstraint('wordid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###
