"""Translate database

Revision ID: f2c79148c4bf
Revises: 5cf708da243f
Create Date: 2023-12-11 14:06:49.778999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2c79148c4bf'
down_revision = '5cf708da243f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=128), nullable=False),
    sa.Column('lastname', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('usercreatedat', sa.TIMESTAMP(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('passwordchanged', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role = ANY(ARRAY['admin','student'])", name='chk_role'),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('korisnik')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('korisnik',
    sa.Column('korisnikid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ime', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('prezime', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('lozinka', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('korisnikstvorenna', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('uloga', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('promijeniolozinku', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.CheckConstraint("uloga::text = ANY (ARRAY['admin'::text, 'ucenik'::text])", name='chk_uloga'),
    sa.PrimaryKeyConstraint('korisnikid', name='korisnik_pkey'),
    sa.UniqueConstraint('email', name='korisnik_email_key')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
